### ISSUE TITLE
No results show

### ISSUE THREAD

**Issue by kazuoteramoto** [thirdy/trademacro#3]
Trying 1.2.0 beta and I'm not getting any results.

When I hit ctrl+p over a item, lets say a Rumi, I get a popup with `submitting` and after a little time another popup that only shows:
```
Rumi's Concoction Granite Flask
--------


```

With a big blank space on the bottom. I'm using Windows 10 (1607) and ahk 1.1.24.00.

**Comment by thirdy** [comment]
gonna release a new version soon, just in case you wanna try it out now:

https://raw.githubusercontent.com/thirdy/longan/master/longan.ahk

I believe I've fixed this issue

**Comment by gvieiraaa** [comment]
I'm having the same problem. Windows 10 / ahk 1.1.24.00

Tried using your new version but the problem persists.

**Comment by thirdy** [comment]
Fixed this problem, please download the script again.

Also posted in reddit:
https://www.reddit.com/r/pathofexile/comments/545js3/tool_poe_trade_macro_buy_your_lifesprig_in_just_1/

**Comment by kazuoteramoto** [comment]
Just reporting back, it is fixed for me, I'm using HEAD.

Thanks!
